### ISSUE TITLE
请问，和其它已安装 pcap 工具是否有冲突？

### ISSUE THREAD

**Issue by SeaHOH** [Macronut/TCPioneer#1]
只了解 pcap 原理，具体实现完全不清楚。
安装此类工具时常有版本相关的风险提示，所以想问你是否了解。
如果已安装工具和内置的不一致，TCPioneer 是否还能正常工作并且不制造出其它问题。

**Comment by Macronut** [comment]
应该不冲突，使用的同时用Wireshark依然能正常工作
版本号因为准备跨平台重新计数😂

**Comment by SeaHOH** [comment]
WinDivert（godivert） 就是 pcap 工具吧，windows 版本使用的。因为先前只有这个版本，没明确说明问题范围。

**Comment by Macronut** [comment]
https://github.com/basil00/Divert

**Comment by SeaHOH** [comment]
>In summary, WinDivert can:
    - capture network packets
    - filter/drop network packets
    - sniff network packets
    - (re)inject network packets
    - modify network packets

不，我的意思是它自己就是个 pcap 工具啊，WinDivert.sys 也是它自己的驱动。
是因为工作于 user-mode，所以和其它 pcap 工具不冲突？

**Comment by SeaHOH** [comment]
我好像有点明白了，即使安装多个驱动，只要文件名不冲突就行。
