### ISSUE TITLE
ERR_CONNECTION_RESET on MEGA (a cloud drive operator)

### ISSUE THREAD

**Issue by toorich** [Macronut/TCPioneer#11]
Tried w-md5, ttl and other methods which listed on `README.md` without be accessed successfully. Including `*.mega.nz`, `*.mega.co.nz` and `*.mega.io`.

**Comment by ygsk100** [comment]
try

```
method=mode3
.mega.nz
.mega.io
.mega.co.nz
mega.nz
mega.io
mega.co.nz
```

**Comment by Macronut** [comment]
Use method "df" as don't fragment for some website

**Comment by toorich** [comment]
The problem doesn't seem to be solved.

**Comment by aries15** [comment]
`method=ttl` works for me.

Though it doesn't work when using MEGA Chrome Extension.

**Comment by Macronut** [comment]
> The problem doesn't seem to be resolved.

you need use: method=ttl,df

**Comment by ghawefzc** [comment]
> > The problem doesn't seem to be resolved.
> 
> you need use: method=ttl,df

@Macronut But it doesn't work for me.
![image](https://user-images.githubusercontent.com/84885601/119752593-e128fe80-becf-11eb-83de-dce97d26a903.png)

**Comment by Macronut** [comment]
https://github.com/Macronut/TCPioneer#how-to-get-the-ttl

**Comment by ghawefzc** [comment]
> https://github.com/Macronut/TCPioneer#how-to-get-the-ttl

@Macronut ERR_SSL_PROTOCOL_ERROR

![image](https://user-images.githubusercontent.com/84885601/120010342-9dd5a980-c00f-11eb-880e-9f6e01097e20.png)

**Comment by Macronut** [comment]
method=ttl,df,sat

**Comment by ghawefzc** [comment]
> method=ttl,df,sat

@Macronut ERR_SSL_PROTOCOL_ERROR

**Comment by ghawefzc** [comment]
> method=ttl,df,sat

@Macronut ERR_TIMED_OUT

**Comment by ghawefzc** [comment]
https://mega.co.nz : ERR_CONNECTION_RESET

![image](https://user-images.githubusercontent.com/84885601/120053276-def3ab00-c05b-11eb-9cb7-da11423c5dc6.png)

**Comment by Franinc** [comment]
有个小问题，和这个issue看起来有关：我最近才意识到好像有针对特定ip+端口发rst包的情况
比如reddit解析的四个结果
```
;; ANSWER SECTION:
reddit.com.		128	IN	A	151.101.193.140
reddit.com.		128	IN	A	151.101.65.140
reddit.com.		128	IN	A	151.101.129.140
reddit.com.		128	IN	A	151.101.1.140

;; Query time: 0 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
```

其中三个被ban，如直接访问[https://151.101.193.140/](https://151.101.193.140/)会得到超时或rst，但80端口却能正常打开[http://151.101.193.140/](http://151.101.193.140/)

![1112111](https://user-images.githubusercontent.com/26399054/123459467-e5ece980-d618-11eb-9e9f-51bab273cbf3.jpg)

没被ban的ip是这样的：

![2223222](https://user-images.githubusercontent.com/26399054/123459107-6fe88280-d618-11eb-8e66-29c33c753636.jpg)

ao3好像443和80都被ban了。

请问这种被ban的ip是不是没有任何办法直连了？
