### ISSUE TITLE
tcp fast open好像有点bug

### ISSUE THREAD

**Issue by Franinc** [Macronut/TCPioneer#14]
```
log=3
method=tfo
www.pixiv.net
.twimg.com（部分子域名支持tcp fast open）
discord.com
.discord.com
```
偶尔www.pixiv.net打不开时，访问所有网站的443端口都会超时：例如tcping企鹅官网443端口超时，但80端口仍然正常。
此时命令行依旧有刷新：
> [104.18.31.199 262144]
> [104.18.30.199 262144]
> [104.18.31.199 262144]

关闭/重启TCPioneer进程后一切恢复正常，但想重新访问p站要再多等一两分钟。复现过一次。

浏览器Cent Browser基于Chromium 86.0.4240.198
TCPioneer 0.5.5

**Comment by Macronut** [comment]
https://github.com/Macronut/TCPioneer/releases/tag/v0.5.6
