### ISSUE TITLE
TCPioneer导致不能正常更新Chrome

### ISSUE THREAD

**Issue by yxh0** [Macronut/TCPioneer#15]
TCPioneer正常工作将会导致Google Chrome无法正常更新，关闭之后就可以正常更新，不知道是什么BUG导致的

**Comment by yxh0** [comment]
> > TCPioneer正常工作将会导致Google Chrome无法正常更新，关闭之后就可以正常更新，不知道是什么BUG导致的
> 
> 如果是按默认配置文件的话*.googleapis.com被接管了，配置文件里的谷歌IP貌似已经死了，可以用`tcpioneer -scanip`去扫可用的IP地址，或者干脆把配置文件的`.googleapis.com=[google.com]`改为`.googleapis.com`（至少Chrome的更新可以走国内）。

问题已经解决，感谢，这个issue算是结束了

**Comment by Macronut** [comment]
the default IP has been removed.if the updated practical address is already available, you can provide it
