### ISSUE TITLE
Telegram desktop can't login in

### ISSUE THREAD

**Issue by xiaofengzhiyu** [Macronut/TCPioneer#16]
Telegram desktop can't login in
telegram的电脑端登陆不上去
网页端 登陆telegram.org完全没有问题

这是什么原因啊?

**Comment by Macronut** [comment]
Telegram uses IP to connect without domain. If the IP is blocked, it cannot be used.
If you have IPv6, you can try to use NAT64 or deploy MTProxy on your local machine and use IPv6 config(https://core.telegram.org/getProxyConfigV6)

**Comment by comet200403** [comment]
在使用TG客户端时需要在 default.conf 中的 #telegram 的 method=ttl 后加入 w-ack,s-seg,https,w-md5
