### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by Franinc** [Macronut/TCPioneer#17]
你好，说明中`domain=ip,ip,...  #this domain will use these IPs`和示例规则如`maps.wikimedia.org=198.35.26.112,208.80.154.240,103.102.166.240,91.198.174.208`这个"高级版"hosts好像有个小问题：

拿`cdnjs.cloudflare.com`举例，它的dns解析结果有4个ip
```
;; ANSWER SECTION:
cdnjs.cloudflare.com.	119	IN	A	104.16.19.94
cdnjs.cloudflare.com.	119	IN	A	104.16.18.94
cdnjs.cloudflare.com.	43	IN	AAAA	2606:4700::6810:135e
cdnjs.cloudflare.com.	43	IN	AAAA	2606:4700::6810:125e
```
其中`104.16.18.94`被ban了，把另外3个ip加进规则`cdnjs.cloudflare.com=104.16.19.94,2606:4700::6810:125e,2606:4700::6810:135e`，正常工作，日志如下：
```
[method=none,https]
[cdnjs.cloudflare.com 1]
[cdnjs.cloudflare.com 28]
[104.16.19.94 256]
```

但是把唯一一个ipv4地址删掉，也就是变成`cdnjs.cloudflare.com=2606:4700::6810:125e,2606:4700::6810:135e`后，程序无视两个ipv6地址开始dns查询ipv4地址并试图访问，日志：
```
[server=208.67.220.220:5353]
[ipv6=true]
[method=none,https]
[cdnjs.cloudflare.com 256]
[cdnjs.cloudflare.com 28]
[208.67.220.220 4]
[104.16.18.94 256]
[104.16.19.94 256]
[104.16.18.94 256]
[104.16.18.94 256]
```

我在win10注册表配置了ipv4优先`Prefer IPv4 over IPv6`，通过此文档[Guidance for configuring IPv6 in Windows for advanced users](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows)，不知道上面的问题是否和这个有关？

虽然能在`C:\Windows\System32\drivers\etc\hosts`添加如`2606:4700::6810:125e cdnjs.cloudflare.com`解决问题，但实在没你这个简便。原版hosts靠多行解决多ip对应单域名导致可读性也不怎样。

**Comment by Macronut** [comment]
You can add ipv4=false before the domain
