### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by miaomiaosoft** [Macronut/TCPioneer#2]
DNS似乎只支持TCP查询？这样我设置 server=local-dns 或 127.0.0.1:53 用本地只开了UDP的DNS就不能解析了。

更新：
多次测试并使用coredns在本地开一个支持TCP查询的服务器似乎也不行，看上去是本地回环的处理上有点问题，目前使用208.67.222.222:5353基本能用，但还是希望能使用本地UDP查询的DNS，修改HOSTS或国内外域名分流解析之类会更方便

**Comment by tec1987** [comment]
cn.nytimes.com  IP被DNS污染解析到一个twitter的IP，其实际使用的是cloudfront CDN

请先确认DNS是否返回正确IP，再看配置文件是否添加该域名

**Comment by tec1987** [comment]
另外，HTTP为明文传输，墙想封的话很容易，直接关键字RST即可，所以对HTTP不要抱有太大希望

**Comment by miaomiaosoft** [comment]
本身是用这个DNS测试的 208.67.222.222:5353
难不成非标准端口TCP解析也被劫持，一直用UDP是没有劫持的

试了下添加两条HOSTS配置确实能打开
.nytimes.com=13.249.171.111
.wsj.com=13.35.67.55

还是希望能支持UDP的本地DNS吧
能支持HTTP当然最好了，不支持也无妨，现在多数网站基本都有了HTTPS

**Comment by tec1987** [comment]
配置文件里用208.67.222.222:5353这个DNS无效？
理论上这个非标端口应该没有污染，可能会丢包劣化，或者考虑其它抗污染方案DoH、DoT、DNSCrypt等，如果不太在意隐私，仅抗污染的话：
可以参考这个：https://github.com/tec1987/Tcp-DNS-proxy
或者用现成的：https://www.233py.com/

**Comment by miaomiaosoft** [comment]
我本地有个纯净的DNS服务器 127.0.0.1:53（不支持本地TCP解析），系统DNS上设置这个用着没问题，上面说的这些防污染方案应该和我这个本地DNS没啥区别。

当server=127.0.0.1:53时：
能打开配置中已有HOSTS的网站，如cn.nytimes.com
但打不开百度，也打不开配置没加HOSTS的网站，如：cn.wsj.com
估计无法向127.0.0.1:53解析，只能用配置中的HOSTS

当server=local-dns时：
只能打开百度之类墙内网站，也不走配置中的HOSTS，也不用系统DNS 127.0.0.1:53
估计只用了运营商下发的DNS，那个DNS本身就被污染

当server=208.67.222.222:5353时：
能打开百度，能打开已加HOSTS的网站，打不开没加HOSTS但理论上使用这个DNS应该能得到纯净IP的网站
所以我猜可能是TCP查询就算非标准端口也会被劫持

测试太多我都有点乱，感觉还是程序本身支持UDP查询就没问题了
极客和红鱼我都不敢用，都是国内服务，随时都可能中断，更别提隐私了。

**Comment by tec1987** [comment]
https://github.com/Macronut/TCPioneer/blob/master/release/windows/config#L9
配置文件里把 这行的注释去掉，使用本地DNS解析试试

**Comment by tec1987** [comment]
server=127.0.0.1:53
#dns64=[2001:67c:27e4::64]:53
local-dns

"server=local-dns" 这么写是无意义的
https://github.com/Macronut/TCPioneer/blob/06f5a87f206113a6f792cad5593a36f0bfec8aee/header/tcpioneer.go#L343

**Comment by miaomiaosoft** [comment]
server=127.0.0.1:53
#dns64=[2001:67c:27e4::64]:53
local-dns

这么配置的话，只有HOSTS内的网站才能打开，百度也不行

**Comment by tec1987** [comment]
。。。。看来这个程序还是不够完善，等作者更新吧

或者你把本地DNS配置为支持TCP查询试试

**Comment by miaomiaosoft** [comment]
是，我也感觉是程序在DNS查询上有点问题，208.67.222.222:5353 这个就算是TCP查询也不应该会被污染，尝试在本地开了个应该是支持TCP查询的DNSCrypt似乎也是不行，可能并不关TCP还是UDP查询的事

**Comment by tec1987** [comment]
go我不熟，大概看了一下，启动时执行了 DNSDaemon()：https://github.com/Macronut/TCPioneer/blob/eb91be549815674cad23cbdbedb0b1af86814282/tcpioneer_windows.go#L62

使用GoDivert(winDiver)对DNS的查询进行过滤：https://github.com/Macronut/TCPioneer/blob/06f5a87f206113a6f792cad5593a36f0bfec8aee/header/udp_windows.go#L26

因为程序必须要在浏览器等客户端连接到服务器之前修改数据包，所以要在本地过滤客户端的DNS查询，与配置文件中的域名匹配，若匹配到域名=IP，则不转发该DNS查询，直接返回指定IP给客户端，然后过滤修改初始握手包并发送；若只匹配到域名：则转发DNS查询到指定服务器，将解析结果发给客户端，过滤握手包并修改发送；若未匹配配域名，则直接转发DNS查询。。。

现在问题来了：在未匹配到域名或者仅匹配到域名时，需要转发DNS查询，当前已经对UDP53端口上的DNS查询做了过滤，所以需要使用非53端口的DNS或者TCP转发。。。
我大致是这么理解的，具体实现未必如此

但是你这个opendns的5353端口居然不正常，建议wireshark抓包看一下，问题也可能出在TCP包过滤上

**Comment by miaomiaosoft** [comment]
谢谢帮助，但抓包分析我不行，等作者看看

**Comment by Macronut** [comment]
已经修复，现在注释掉或不设置DNS即表示使用本地或其它抗污染DNS。
