### ISSUE TITLE
有些疑问...

### ISSUE THREAD

**Issue by forodo** [Macronut/TCPioneer#22]
不是很懂这个工具的原理，因此有两点疑问希望解答~

1. 通过该工具访问被屏蔽的网站时，**第三方是否能看到 SNI**（域名）？或者说第三方看到的是什么样的？
`我看过那个 PDF 论文，但是对于业余的我来说这些太底层、高深了，只知道涉及到伪造 TCP 数据包...`
2. 如何 DNS 分流解析？
`即只想让被屏蔽的域名走国外无污染 DNS，其他正常域名都还走国内普通 DNS，避免国外 DNS 解析国内网站不尽人意...`
`或者该工具可以支持设置 2 个 DNS，配置文件中的域名通过 DNS A 解析，没有匹配到的域名通过 DNS B 解析，这样就很完美了~`

无论如何，先感谢作者写的这个工具~

**Comment by Macronut** [comment]
1.Experienced humans can guess the original SNI, machines can not, you can see them by wireshark.
2.https://github.com/Macronut/phantomsocks

**Comment by forodo** [comment]
我看了下 phantomsocks 的介绍。
```
phantomsocks -socks 0.0.0.0:1080
```
这个工具这样启动的话，是不是只有**通过该代理**才会修改数据包？不会影响到其他网络链接及 DNS 请求吧？
如果是这样的话搭配浏览器 SwitchyOmega 扩展管理起来就很方便了，完全满足我的需求~

而 Redirect 模式是不是就和 TCPioneer 的差不多，会对整个设备的网络进行劫持修改？
