### ISSUE TITLE
About scan IP

### ISSUE THREAD

**Issue by XCwosjw** [Macronut/TCPioneer#25]
I scanned Google's IP range using "tcpioneer -scanip" and got some IPs. But some of these IPs cannot be used for "www.google.com". How should I differentiate them?

**Comment by XCwosjw** [comment]
I scanned Google's IP range using "tcpioneer -scanip" and got some IPs. But some of these IPs cannot be used for "www.google.com". How should I differentiate them?

**Comment by XCwosjw** [comment]
Also you may be able to add parameters to select the configuration file.

**Comment by Macronut** [comment]
> I scanned Google's IP range using "tcpioneer -scanip" and got some IPs. But some of these IPs cannot be used for "www.google.com". How should I differentiate them?

tcpioneer -scanip x.x.x.x/x -scanurl https://www.google.com

**Comment by Macronut** [comment]
> Also you may be able to add parameters to select the configuration file.

please use phantomsocks

**Comment by awslawsl233** [comment]
@Macronut 
> `tcpioneer -scanip x.x.x.x/x -scanurl https://www.google.com`
I don't think this will work, as Google will return 302 to `https://www.google.com.hk`, and now TCPioneer only check for 200.

**Comment by Macronut** [comment]
If your region will be redirected by Google by default, you should add ncr or directly scan the domain name in your region.

**Comment by awslawsl233** [comment]
> If your region will be redirected by Google by default, you should add ncr or directly scan the domain name in your region.

Just use `www.google.com.hk` , because https://www.google.com/ncr is also a 302 redirect.

**Comment by XCwosjw** [comment]
thank you
