### ISSUE TITLE
排除解析为中国IP的网站

### ISSUE THREAD

**Issue by miaomiaosoft** [Macronut/TCPioneer#3]
因懒于频繁添加被和谐网站，所以使用匹配所有主流后缀的方式强行全局：
#LEVEL3
ttl=12
md5=true
mss=0
.com
.org
.net

然后使用发现大多数网站全局下都没问题，但小部分国内网站会400或被重置之类访问失败，经测试将这类网站添加到此配置项后可以正常访问（我就当白名单用了），例如：
#LEVEL1
ttl=0
mss=0
md5=false
.cn
youdao.com
.youdao.com

然而国内网站的域名列表也是巨大无比，所以就想能否增加一项配置功能，忽略解析IP为中国的网站，这可能还需要调用一个外置的国内IP数据库

顺便说下一些台湾网站适合这个配置：
#LEVEL2
ttl=6
md5=true
mss=0
metroradio.com.hk
.metroradio.com.hk
cdns.com.tw
.cdns.com.tw
ltn.com.tw
.ltn.com.tw
gvm.com.tw
.gvm.com.tw
nextmag.com.tw
.nextmag.com.tw
cts.com.tw
.cts.com.tw
gamebase.com.tw
.gamebase.com.tw

**Comment by Macronut** [comment]
Get the latest release and edit config like this:
-
ttl=12
md5=true
server=8.8.8.8:53
log=2

subdomain=0

\#Protectlist
0.0.0.0\/0

\#Whitelist
ttl=0
md5=0
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
100.64.0.0/10
Othe IP of "LAN"

OR
-
ttl=12
md5=true
server=8.8.8.8:53
log=2

subdomain=6
.com
.net
.org
#Other Domain

#Protectlist
0.0.0.0/0

#Whitelist
ttl=0
md5=0
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
100.64.0.0/10
#Othe IP of "LAN"

In your case, you can set the TTL beforce domain or IP of taiwan like this
-
ttl=6
.tw

ttl=6
1.34.0.0/15
1.160.0.0/12
1.200.0.0/16
27.0.152.0/22
27.51.0.0/16
27.52.0.0/15
27.96.224.0/19
...

**Comment by SeaHOH** [comment]
精确度高的列表会比较大，能不能做成支持外联以方便单独维护列表？

**Comment by Macronut** [comment]
可以考虑，不过目前还是写个更新脚本从github上取域名列表或者IP段比较独立

**Comment by SeaHOH** [comment]
外联到单独的文件主要是方便维护，主配置搞得太大使用上有所不便。

**Comment by Macronut** [comment]
你指的是使用上？
那可以改为主配置文件加引用，像gfwlist和各个国家的IPBlock等可以自动生成的放其它配置文件里，但格式任然是一样的

**Comment by SeaHOH** [comment]
比如这样
```
# config
ttl=0
conf=cn_ip
```
```
# cn_ip
1.0.1.0/24
1.0.2.0/23
1.0.8.0/21
1.0.32.0/19
1.1.0.0/24
1.1.2.0/23
1.1.4.0/22
1.1.8.0/21
1.1.16.0/20
...
```

**Comment by miaomiaosoft** [comment]
试了下，似乎不可用

ttl=12
md5=true
#server=8.8.8.8:53
log=2

subdomain=6
.com
.net
.org
#Other Domain

#Whitelist
ttl=0
md5=0
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
100.64.0.0/10
#Othe IP of "LAN"
#www.wdku.net=119.147.136.190
119.147.136.0/24

打开www.wdku.net会被重置，或者我配置改的有问题？

**Comment by Macronut** [comment]
#表示这行是注释，你注释掉了DNS和你要用的域名
#Othe IP of "LAN"这行意思是填写所有你不需要处理的IP，比如你在大陆就要填写所有大陆IP段
额外增加需要处理的域名和IP也不能放在#Whitelist开始全关闭的声明之后

**Comment by miaomiaosoft** [comment]
注释DNS不是因为只有注释了才能使用系统DNS么
看的我有点乱，有点不能理解，能否麻烦帖上一份较完整配置，可以先不管tw后缀

使用系统DNS
处理常见后缀 .com .net .org
不处理中国IP的网站

**Comment by Macronut** [comment]
你系统的DNS是抗污染的？
那就你上面的配置在Whitelist部分把境内IP段填全

**Comment by miaomiaosoft** [comment]
系统DNS肯定是纯净的，否则用这个就没意义
其实原本就是用的完整的国内IP段，只不过帖上来会太长所以只取了其中一个网站，我以为你能GET到这个提示

IP段用的这个 https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt

**Comment by Macronut** [comment]
我测试了你的配置文件，没有出现问题，你是不是没有更新我回复时更新的0.2.2版本？

**Comment by miaomiaosoft** [comment]
是下的0.2.2
重新下载覆盖也是同样的日期，应该没错

**Comment by miaomiaosoft** [comment]
你那测试正常会不会与网络环境有关，我是联通
应该要看Log之类才知道会不会被处理

**Comment by Macronut** [comment]
可以再更新一下0.2.3，但应该和你要的全局关系不大
现在是wikipedia这类境外网站可以上，然后这个境外网站不能上？
你设置log=3只访问这个网站发来看看吧

**Comment by miaomiaosoft** [comment]
0.2.3
配置如上后面附加全部国内IP段
log=3
浏览器测试时频繁重启，应该可以排除缓存干扰结果

这个网站 https://www.wdku.net/ 有时能打开
当能打开时 点击里面的链接跳转到二级域名页面又会打不开
然后再返回到 https://www.wdku.net/ 也打不开了
维基百科基本上一直都能打开

打不开时日志是样 [IP 5]

**Comment by Macronut** [comment]
是浏览器重启还是这个程序重启？控制台下崩溃时有日志的
[IP 5]前面的IP是你要访问的域名的IP么

**Comment by miaomiaosoft** [comment]
重启浏览器，程序的配置没变重启程序应该效果也不会变
没遇到什么崩溃
前面的IP就是 https://www.wdku.net/ 的IP

**Comment by Macronut** [comment]
原因找到了，更新一下

**Comment by miaomiaosoft** [comment]
已更新测试
问题解决
谢谢！

**Comment by Macronut** [comment]
再更新下试试，优化了性能

**Comment by miaomiaosoft** [comment]
025试了，IP段不失效了，CPU占用似乎也略有增加

**Comment by Macronut** [comment]
CPU占用增加？不应该啊，现在对IP段的查找只发生在DNS阶段，连接时不查找的
功能部分没问题是吧？

**Comment by miaomiaosoft** [comment]
只发现IP段不生效，功能没问题，CPU占用我印象之前一直是0，现在偶尔看到有1%-2%，不过这点占用可以忽略

**Comment by Macronut** [comment]
IP段不生效？0.25版本可以正常排除境内IP吗？

**Comment by miaomiaosoft** [comment]
对，国内IP排除失效

**Comment by Macronut** [comment]
重新获取0.2.5看一下，没问题我就可以close了

**Comment by miaomiaosoft** [comment]
已更新测试，问题解决
