### ISSUE TITLE
优化DNS解析策略

### ISSUE THREAD

**Issue by EXSERENS** [Macronut/TCPioneer#4]
Google的IPv6地址目前没有被黑洞，而是仅域名受SNI照顾。此时可以配置中指定IPv4地址，而IPv6地址从DNS处（可指定内置/系统DNS）解析返回。配置文件可以单独指定该策略针对IPv4/IPv6。
同时，希望支援类似 dns.google 这种DNS定义方式。

**Comment by Macronut** [comment]
Get the latest release and edit config, for example:
-
ttl=12
md5=true
server=dns.google:53

#The following domain will be set IPv4 and get IPv6 from DNS
ipv6=true
www.google.com=216.58.204.168

#The following domain will be set IPv4 and without IPv6 unless you set it
ipv6=false
.googleusercontent.com=108.177.127.133
.wikipedia.org=198.35.26.96,2620:0:863:ed1a::1

#The following domain will get IPv4/IPv6 from DNS
ipv6=true
.wikipedia.org

#The following domain will get IPv4 from DNS and without IPv6
ipv6=false
upload.wikimedia.org
