### ISSUE TITLE
[Feature] Add Protect for other tcp protocal

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [Macronut/TCPioneer#6]
in my net env, the github's ssh (port 22) connect not stable, it seems to be block.

after read the code, seems like the protect on 443 port is a generic tcp protect act.
i think this also can do on the 22 port . so i add a ```case 22:``` on it like [this](https://github.com/Lyoko-Jeremie/TCPioneer/commit/552812bb94f51fbd5a07191d2ee9ef482a054ff5) .
after my test, it feel like work well.

and i think that maybe we can add a func to set the additional protect tcp port on the config file.

the config can seems like this:

```
ExtraProtectTcpPort= 22
ExtraProtectTcpPort= 21
```

and read it when start up.

**Comment by Macronut** [comment]
You can edit the config like this:
[your server ip]:22

"header/tcpioneer.go +537"

**Comment by Lyoko-Jeremie** [comment]
emmmm, if i want to protect all the ssh protocal on 22 port , how to config it ?

**Comment by Macronut** [comment]
:22

header/tcp.go +400

//domain or ip block of you servers need be configured

**Comment by Lyoko-Jeremie** [comment]
thanks~~~

**Comment by Lyoko-Jeremie** [comment]
so sorry for that . but, i still have a question. 

why this code only for 443 ? what means dose it doing ? i cannot fully understand this code.

https://github.com/Macronut/TCPioneer/blob/3e835575ed00f415b9d4808a6ce7d707a0929089/header/tcp.go#L588-L656

and then, why other pack dont need do it ?
https://github.com/Macronut/TCPioneer/blob/3e835575ed00f415b9d4808a6ce7d707a0929089/header/tcp.go#L657-L659

emm 🤔

**Comment by Macronut** [comment]
https have SNI so it needs to break from the middle of SNI, 
other protocols are usually enough to break from the middle of the packets.
