### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aries15** [Macronut/TCPioneer#9]
版本：0.5.1

我不会Go。观察输出日志，`[xxx 0]`代表的是none，1代表的是ttl，4代表的是w-md5

但当我设置：

```
log=2
ttl=12
mss=512
method=w-md5
server=8.8.8.8:53

method=none
ipv6=false
example.com=127.0.0.1
```

用`curl example.com`，结果只有一条`[example.com 1]`。当注释掉ipv6=false后，结果是

```
[example.com 1]
[example.com 0]
[8.8.8.8 4]
```

这是expected的吗？

我还想和hosts结合使用。根据测试，当hosts中存在对应条目时，无论加不加`server`，本软件似乎都不会匹配请求。当不加`server`并且hosts中也不存在条目时，仍没有匹配请求。似乎只有存在server并且不存在hosts本软件才能匹配到

另外默认配置里的method=proxy会报错

---

以上算是BUG Report吧。另外还有两个问题：

* 怎么判断什么时候用ttl，什么时候用w-md5呢？
* mss=512有什么用

**Comment by Macronut** [comment]
The domains from the a method to the next method will use the methods specified by the nearest method above.
If you want to use hosts, please put the hosts in the program directory.
Set the maximum segment size[https://en.wikipedia.org/wiki/Maximum_segment_size] can make the TCP packet returned by the server smaller

**Comment by Macronut** [comment]
The domains from a method to the next method will use the methods specified by the nearest method above.
If you want to use hosts, please put the hosts in the program directory.
Set the maximum segment size[https://en.wikipedia.org/wiki/Maximum_segment_size] can make the TCP packet returned by the server smaller

**Comment by aries15** [comment]
第一句我知道，我是想问我设置了method=none但是log显示的是1不是0，去掉`=127.0.0.1`才是0。如果没问题就行

第二句，我试了一下把`hosts`文件放在`tcpioneer.exe`同一个文件夹下没有用啊……

**Comment by smell-of-rain** [comment]
Can TCPioneer randomize TCP segment sizes to confuse heuristics?

**Comment by aries15** [comment]
最近感觉我这里w-md5无法解决像针对github.com一样的劣化了，但还是能过RST
